# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/krul/Documents/tp-c-2iz

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/krul/Documents/tp-c-2iz/build

# Include any dependencies generated for this target.
include src/with_procs/CMakeFiles/with_procs.dir/depend.make

# Include the progress variables for this target.
include src/with_procs/CMakeFiles/with_procs.dir/progress.make

# Include the compile flags for this target's objects.
include src/with_procs/CMakeFiles/with_procs.dir/flags.make

src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.o: src/with_procs/CMakeFiles/with_procs.dir/flags.make
src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.o: ../src/with_procs/with_procs.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/krul/Documents/tp-c-2iz/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.o"
	cd /home/krul/Documents/tp-c-2iz/build/src/with_procs && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/with_procs.dir/with_procs.c.o -c /home/krul/Documents/tp-c-2iz/src/with_procs/with_procs.c

src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/with_procs.dir/with_procs.c.i"
	cd /home/krul/Documents/tp-c-2iz/build/src/with_procs && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/krul/Documents/tp-c-2iz/src/with_procs/with_procs.c > CMakeFiles/with_procs.dir/with_procs.c.i

src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/with_procs.dir/with_procs.c.s"
	cd /home/krul/Documents/tp-c-2iz/build/src/with_procs && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/krul/Documents/tp-c-2iz/src/with_procs/with_procs.c -o CMakeFiles/with_procs.dir/with_procs.c.s

# Object files for target with_procs
with_procs_OBJECTS = \
"CMakeFiles/with_procs.dir/with_procs.c.o"

# External object files for target with_procs
with_procs_EXTERNAL_OBJECTS =

src/with_procs/libwith_procs.a: src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.o
src/with_procs/libwith_procs.a: src/with_procs/CMakeFiles/with_procs.dir/build.make
src/with_procs/libwith_procs.a: src/with_procs/CMakeFiles/with_procs.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/krul/Documents/tp-c-2iz/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C static library libwith_procs.a"
	cd /home/krul/Documents/tp-c-2iz/build/src/with_procs && $(CMAKE_COMMAND) -P CMakeFiles/with_procs.dir/cmake_clean_target.cmake
	cd /home/krul/Documents/tp-c-2iz/build/src/with_procs && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/with_procs.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/with_procs/CMakeFiles/with_procs.dir/build: src/with_procs/libwith_procs.a

.PHONY : src/with_procs/CMakeFiles/with_procs.dir/build

src/with_procs/CMakeFiles/with_procs.dir/clean:
	cd /home/krul/Documents/tp-c-2iz/build/src/with_procs && $(CMAKE_COMMAND) -P CMakeFiles/with_procs.dir/cmake_clean.cmake
.PHONY : src/with_procs/CMakeFiles/with_procs.dir/clean

src/with_procs/CMakeFiles/with_procs.dir/depend:
	cd /home/krul/Documents/tp-c-2iz/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/krul/Documents/tp-c-2iz /home/krul/Documents/tp-c-2iz/src/with_procs /home/krul/Documents/tp-c-2iz/build /home/krul/Documents/tp-c-2iz/build/src/with_procs /home/krul/Documents/tp-c-2iz/build/src/with_procs/CMakeFiles/with_procs.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/with_procs/CMakeFiles/with_procs.dir/depend

