# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.o: ../src/no_procs/no_procs.h
src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.o: ../src/with_procs/with_procs.c
src/with_procs/CMakeFiles/with_procs.dir/with_procs.c.o: ../src/with_procs/with_procs.h

