# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# compile C with /usr/bin/cc
C_DEFINES = 

C_INCLUDES = -I/home/krul/Documents/tp-c-2iz/src/with_procs -I/home/krul/Documents/tp-c-2iz/src/no_procs

C_FLAGS = --coverage -std=gnu99

